config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :events do
    resources :products do#, except:[:edit, :destroy]
      resources :comments, except:[:index, :show, :edit, :update, :destroy]
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  validates :content, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :products
    validates :name, presence: true
    validates :date, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  belongs_to :event
  validates :name, presence: true
  validates :about, presence: true
  validates :member, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    if params[:comment][:commenter] == ""
      params[:comment][:commenter] = "じゃっくん"
    end
    Comment.create(create_params)
    redirect_to controller: :products, action: :show, id: params[:product_id]
  end

  private
    def create_params
      params.require(:comment).permit(:commenter, :content).merge(product_id: params[:product_id])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :set_event, only: [:show]

    # GET /events
    def index
        @events = Event.all
    end

    # GET /events/1
    def show
    end

    # GET /events/new
    def new
        @event = Event.new
    end

    # GET /event/1/edit
    def edit
    end

    # POST /events
    def create
        @event = Event.new(event_params)

        respond_to do |format|
            if @event.save
                format.html { redirect_to events_path, notice: 'イベントを作成しました'}
                format.json { render :show, status: :created, location: @event }
            else
                format.html { render :new }
                format.json { render json: @event.errors, status: :unprocessable_entity }
            end
        end
    end

    private
        def set_event
            @event = Event.find(params[:id])
        end

        def event_params
            params.require(:event).permit(:name, :date)
        end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @event = Event.find(params[:event_id])
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @comment = Comment.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to event_products_path, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :about, :member, :need_people, :reference_url).merge(event_id: params[:event_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/comment/new.html.erb
<h1>Comment#new</h1>
<p>Find me in app/views/comment/new.html.erb</p>

app/views/events/_form.html.erb
<%= form_with(model: @event, local:true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">イベント名</h6>
    <%= form.text_field :name, id: :event_name, class:"w-100"%>
  </div>
  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">日にち</h6>
    <%= form.date_field :date, id: :event_date, class:"w-100"%>
  </div>
  <div class="actions text-center">
    <%= form.submit "作成", class:"btn btn-primary w-50"%>
  </div>

<% end %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mx-auto" style="max-width: 500px;">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col p-5 w-100 h-100 d-inline-block">イベント名</th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%=link_to event.name, event_products_path(event.id), class: "w-100 h-100 d-inline-block", style:"padding: 1.2em; font-size: 1.3em;" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>


<br>
<div class="text-right mx-auto" style="max-width: 500px">
  <%= link_to 'イベントを追加', new_event_path, class: "btn btn-primary" %>
</div>

app/views/events/new.html.erb
<div class="mb-3">
    イベントについて教えてください
</div>

<%= render 'form', event: @event %>

<%= link_to '戻る', root_path, class:"btn btn-outline-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JackAdvice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=link_to "jack Advice!", root_path, class:"text-center mb-5 mt-5", id:"titleOfAll"%>
    <%= yield %>
  </body>
</html>

app/views/products/_comments_form.html.erb
<%= form_with(model: [@event,@product,@comment], local: true, url: event_product_comments_path(product_id: @product.id)) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    投稿者(20文字まで)<br>
    <%= form.text_field :commenter, id: :comment_commenter, maxlength: 20, class: "w-100 p-2", placeholder: "じゃっくん"%>
  </div>

  <div class="field h-50">
    コメント<br>
    <%= form.text_area :content, id: :comment_content, class: "w-100 p-2", style:"height: 100px"%>
  </div>

    <div class="text-center">
      <%= button_tag type: "submit", class: "btn btn-primary w-50" do %>
        投稿する<i class="icon-arrow-right"></i>
      <% end %>
    </div>
<% end %>

app/views/products/_form.html.erb
<%= form_with(model: [@event,@product], local: true, url: event_products_path) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">プロダクト名</h6>
    <%= form.text_field :name, id: :product_name, class:"w-100"%>
  </div>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">概要</h6>
    <%= form.text_area :about, id: :product_about, class:"w-100"%>
  </div>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">メンバー</h6>
    <%= form.text_field :member, id: :product_member, class:"w-100"%>
  </div>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">こんなメンバーに来てほしい！</h6>
    <%= form.text_area :need_people, id: :product_need_people, class:"w-100" %>
  </div>

  <div class="field mb-4">
    <h6 class="mb-2 font-weight-bold">参考URL</h6>
    <%= form.text_field :reference_url, id: :product_reference_url, class:"w-100"%>
  </div>

  <div class="actions text-center">
    <%= form.submit "作成", class:"btn btn-primary w-50"%>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="mx-auto" style="max-width: 500px;">
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th scope="col p-5 w-100 h-100 d-inline-block">プロダクト名</th>
      </tr>
    </thead>

    <tbody>
      <% @event.products.each do |product| %>
        <tr>
          <td><%=link_to product.name, event_product_path(@event, product), class: "w-100 h-100 d-inline-block", style:"padding: 1.2em; font-size: 1.3em;" %></td>
          <%# <td><%= link_to 'Edit', edit_product_path(product)</td> %>
          <%# <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } </td> %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<div class="text-right mx-auto" style="max-width: 500px">
  <%= link_to "戻る", events_path, class:"btn btn-outline-primary float-left" %>
  <%= link_to 'プロダクトを追加', new_event_product_path, class: "btn btn-primary" %>
</div>

app/views/products/new.html.erb
<div class="mb-3">
  プロダクトについて教えてください
</div>


<%= render 'form', product: @product %>

<%= link_to '戻る', event_products_path, class:"btn btn-outline-primary" %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="mb-4">
  <h6 class="mb-2 font-weight-bold">プロダクト名</h6>
  <p class="fs-15"><%=@product.name%></p>
</div>

<div class="mb-4">
  <h6 class="mb-2 font-weight-bold">概要</h6>
  <p class="fs-15"><%=@product.about%></p>
</div>

<div class="mb-4">
  <h6 class="mb-2 font-weight-bold">メンバー</h6>
  <p class="fs-15"><%=@product.member%></p>
</div>

<div class="mb-4">
  <h6 class="mb-2 font-weight-bold">こんなメンバーに来てほしい！</h6>
  <p class="fs-15"><%=@product.need_people%></p>
</div>

<div class="mb-4">
  <h6 class="mb-2 font-weight-bold">参考URL</h6>
  <p class="fs-15"><%=@product.reference_url%></p>
</div>

<div class="mt-5" style="position: relative;">
  <h4 class="w-100"  style="border-top: solid 0.5px; padding-top: 0.3em">みんなのコメント</h4>
  <%=link_to '更新', event_product_path(@product), style:"position: absolute; right:0px; top:0px;", class: "mt-1 btn btn-outline-primary"%>
</div>

<br>
<div class="p-1 mb-4" style="height:300px;overflow:auto;background-color:#eee;">
  <% @product.comments.reverse_each do |comment| %>
    <div class="border p-3 my-1" style="background-color: #fff; position:relative;">
      投稿者: <%=comment.commenter %>
      <br>
      <%= simple_format comment.content %>
      <%= comment[:created_at].strftime("%Y-%m-%d %H:%M %S")+"s" %>
    </div>
  <% end %>
</div>

<%=render 'comments_form', product: @product %>
<%=link_to "戻る", event_products_path, class:"btn btn-outline-primary"%>
<br><br><br><br>